[build]
	command = "npm run build"
	publish = "dist"
	base = "."

[build.environment]
	# Set this in Netlify UI to your API base, e.g. https://kex-api.onrender.com
	# Netlify will expose it to Vite at build time
	VITE_API_BASE = "https://your-api-domain" 