[build]
	command = "npm --prefix apps/web install && npm --prefix apps/web run build"
	publish = "apps/web/dist"

[build.environment]
	NODE_VERSION = "20"
	# Set VITE_API_BASE in the Netlify UI to your Render API URL 

# SPA fallback: serve index.html for client-side routes like /checkout
[[redirects]]
from = "/*"
to = "/index.html"
status = 200 